AcademicShare.Web/Models/DbSet/Post.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace AcademicShare.Web.Models.Dtos;

public class Post
{
    [Key]
    public Guid PostId { get; set; }
    [Required, MaxLength(80, ErrorMessage = "Title can't be extended 80 character")]
    public required string Title { get; set; }
    [Required, MaxLength(10000, ErrorMessage = "Content can't be extended 10000 character")]
    public required string Content { get; set; }
    [Required, MaxLength(200, ErrorMessage = "Resume can't be extended 200 character")]
    public required string Resume { get; set; }
	public required string Image { get; set; }
    public required string Teacher { get; set; }
    public virtual required User Posts { get; set; }
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();
    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}

AcademicShare.Web/Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AcademicShare.Web.Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using AcademicShare.Web.Models;
using AcademicShare.Web.Models.Dtos;
using AutoMapper;
using AcademicShare.Web.Models.Paginated;
using System;

namespace AcademicShare.Web.Controllers;

[Authorize]
public class PostsController : Controller
{
    private readonly AcademicShareDbContext _context;
    private readonly SignInManager<User> _signInManager;
    private readonly UserManager<User> _userManager;
    private readonly IWebHostEnvironment _hostEnvironment;
    private readonly IMapper _mapper;

    public PostsController(
        AcademicShareDbContext context,
        UserManager<User> userManager,
        SignInManager<User> signInManager,
        IWebHostEnvironment hostEnvironment,
        IMapper mapper)
    {
        _context = context;
        _signInManager = signInManager;
        _userManager = userManager;
        _hostEnvironment = hostEnvironment;
        _mapper = mapper;
    }

    [HttpGet]
    public async Task<IActionResult> Index(
        string searchString,
        int? pageNumber,
        string sortOrder)
    {
        ViewData["CurrentSort"] = sortOrder;
        if (searchString != null)
        {
            pageNumber = 1;
        }

        if (_context.Posts == null) return Problem("Entity set is null.");

        var posts = from m in _context.Posts
                    select m;

        if (!string.IsNullOrEmpty(searchString))
            posts = posts.Where(s => s.Title!.Contains(searchString));

        ViewBag.User = await _context.Users.FirstOrDefaultAsync(p => p.Id == _userManager.GetUserId(User));

        int pageSize = 9;
        return View(
            await PaginatedList<Post>.CreateAsync(
            posts.OrderByDescending(c => c.CreatedAt)
                .AsNoTracking()
                .Include(p => p.Posts)
                .Include(p => p.Comments)
                .Include(p => p.Likes),
            pageNumber ?? 1, pageSize));
    }

    // GET: Posts/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null) return NotFound();

        var post = await _context.Posts
            .FirstOrDefaultAsync(m => m.PostId.Equals(id));
        if (post == null) return NotFound();

        return View(post);
    }

    public IActionResult Create() => View();


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(
        [Bind(include: "Title,Content,Image,Teacher,Resume")] GetPostDto post)
    {
        if (ModelState.IsValid)
        {
            var fileName = string.Empty;
            if (post.Image is not null)
            {
                var wwwRootPath = _hostEnvironment.WebRootPath;
                fileName = Guid.NewGuid().ToString() + "_" + post.Image.FileName;
                var path = Path.Combine(wwwRootPath + "/imagesPost/", fileName);

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await post.Image.CopyToAsync(fileStream);
                }

            }
            else fileName = "default.png";

            Console.WriteLine(post.Resume);

            var newPost = _mapper.Map<Post>(post);
            newPost.Image = fileName;
            newPost.CreatedAt = DateTime.Now;
            newPost.UpdatedAt = DateTime.Now;
            newPost.Posts = await _userManager.GetUserAsync(User);

            _context.Add(newPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(post);
    }

    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null) return NotFound();

        var post = await _context.Posts.AsNoTracking().FirstOrDefaultAsync(p => p.PostId.Equals(id));
        if (post == null) return NotFound();
        return View(post);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(
        Guid id,
        [Bind("PostId,Title,Content,Image,Teacher,CreatedAt,UpdatedAt,UserId")] Post post)
    {
        if (!id.Equals(post.PostId)) return NotFound();

        if (ModelState.IsValid)
        {
            try
            {
                var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == post.Posts.Id);
                post.Posts = user!;
                post.UpdatedAt = DateTime.Now;
                _context.Update(post);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PostExists(post.PostId)) NotFound();
                else throw;
            }
            return RedirectToAction(nameof(Index));
        }
        return View(post);
    }

    // GET: Posts/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null) NotFound();

        var post = await _context.Posts.FirstOrDefaultAsync(m => m.PostId.Equals(id));

        if (post == null) NotFound();

        return View(post);
    }

    // POST: Posts/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var post = await _context.Posts.FindAsync(id);
        if (post != null)
            _context.Posts.Remove(post);

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    [HttpGet, ActionName("ViewPost")]
    public async Task<IActionResult> ViewPost(Guid id)
    {
        if (id.Equals(null)) return NotFound();

        var post = await _context.Posts.AsNoTracking().FirstOrDefaultAsync(p => p.PostId.Equals(id));

        if (post == null) return NotFound();

        ViewPostDto postView = _mapper.Map<Post, ViewPostDto>(post);

        return View(postView);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ViewPost(
        [Bind(include: "CommentContent,PostId")]
        ViewPostDto Postcomment)
    {
        if (Postcomment == null) return NotFound();
        if (ModelState.IsValid)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == _userManager.GetUserId(User));

            #pragma warning disable CS8601 // Possible null reference assignment.
            var Comment = new Comment
            {
                Content = Postcomment.CommentContent,
                Post = await _context.Posts.FirstOrDefaultAsync(p => p.PostId.Equals(Postcomment.PostId)),
                User = user,
                CreatedAt = DateTime.Now,
            };
            #pragma warning restore CS8601 // Possible null reference assignment.
            _context.Comments.Add(Comment);

            await _context.SaveChangesAsync();

            return RedirectToAction("ViewPost", new { id = Postcomment.PostId });
        }
        return View(Postcomment);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> IndexLike(
        [Bind(include: "PostId")]
        ViewPostDto posts)
    {
        if (posts == null) return NotFound();
        var existingLikes = _context.Likes.Where(l => l.Post.PostId.Equals(posts.PostId) && l.User.Id == _userManager.GetUserId(User));

        if (existingLikes.Any())
        {
            _context.Likes.RemoveRange(existingLikes);
            await _context.SaveChangesAsync();

            return RedirectToAction("ViewPost", new { id = posts.PostId });
        }

        #pragma warning disable CS8601 // Possible null reference assignment.
        var like = new Like
        {
            Post = await _context.Posts.FirstOrDefaultAsync(p => p.PostId.Equals(posts.PostId)),
            User = await _context.Users.FirstOrDefaultAsync(u => u.Id == _userManager.GetUserId(User)),     
        };
        #pragma warning restore CS8601 // Possible null reference assignment.
        _context.Likes.Add(like);

        await _context.SaveChangesAsync();
        return RedirectToAction("ViewPost", new { id = posts.PostId });
    }

    [HttpGet]
    public async Task<IActionResult> LikedPosts(
        string UserName,
        string searchString,
        int? pageNumber,
        string sortOrder)
    {
        ViewData["CurrentSort"] = sortOrder;

        if (searchString != null)
        {
            pageNumber = 1;
        }

        var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == _userManager.GetUserId(User));
        var likedPosts = _context.Likes.Where(l => l.User.Id == user.Id).Select(l => l.Post.PostId);
        var posts = _context.Posts.Where(p => likedPosts.Contains(p.PostId));

        var likedPostsList = from m in posts
                             select m;
        
        if (!string.IsNullOrEmpty(searchString))
            likedPostsList = likedPostsList.Where(s => s.Title!.Contains(searchString));

        ViewBag.User = await _context.Users.FirstOrDefaultAsync(p => p.Id == _userManager.GetUserId(User));
        
        int pageSize = 9;
        return View(await PaginatedList<Post>.CreateAsync(
            likedPostsList.OrderByDescending(c => c.CreatedAt).AsNoTracking(), pageNumber ?? 1, pageSize));
    }

    private bool PostExists(Guid id) => _context.Posts.Any(e => e.PostId.Equals(id));
}

AcademicShare.Web/Controllers/ProfileController.cs
using AcademicShare.Web.Context;
using AcademicShare.Web.Models;
using AcademicShare.Web.Models.Dtos;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AcademicShare.Web.Controllers;

public class ProfileController : Controller
{
    private readonly AcademicShareDbContext _context;
    private readonly SignInManager<User> _signInManager;
    private readonly UserManager<User> _userManager;
    private readonly IWebHostEnvironment _hostEnvironment;
    private readonly IMapper _mapper;


    public ProfileController(
        AcademicShareDbContext context, 
        UserManager<User> userManager, 
        SignInManager<User> signInManager, 
        IWebHostEnvironment hostEnvironment,
        IMapper mapper)
    {
        _hostEnvironment = hostEnvironment;
        _context = context;
        _signInManager = signInManager;
        _userManager = userManager;
        _mapper = mapper;
    }
    
    [Authorize]
    [HttpGet("Profile/{UserName}")]
    public async Task<IActionResult> Index(string? UserName)
    {
        var user = await _context.Users
            .AsNoTracking()
            .FirstOrDefaultAsync(m => m.UserName!.Equals(UserName));
            
        if (user is null) return NotFound();

        var profile = await _context.Profiles
            .AsNoTracking()
            .FirstOrDefaultAsync(p => p.User.Id.Equals(user.Id));

        if (profile is null) return NotFound();

        var viewProfile = _mapper.Map<ViewProfileDto>(user);

        return View(viewProfile);
    }

    [Authorize]
    [HttpPost("Profile/{UserName}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(
        ViewProfileDto UserProfile)
    {
        if (UserProfile.Follow is not null)
        {
            var user = await _userManager.GetUserAsync(User);
            var followed = await _context.Users.FirstOrDefaultAsync(u => u.UserName == UserProfile.UserName);

            if (_context.Follow.Any(f => f.FollowerId.Equals(user!.Id) && f.FollowedId.Equals(followed!.Id)))
            {
                var followRemove = await _context.Follow.FirstOrDefaultAsync(f => f.FollowerId.Equals(user.Id) && f.FollowedId.Equals(followed.Id));
                
                _context.Follow.Remove(followRemove!);

                await _context.SaveChangesAsync();

                return RedirectToAction("Index", new { UserName = followed.UserName });
            }

            var follow = new Follow
            {
                FollowerId = user.Id,
                FollowedId = followed.Id
            };

            _context.Follow.Add(follow);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { UserName = followed.UserName });
        }
        if (ModelState.IsValid)
        {
            string fileNameBanner;
            string fileNameProfilePicture;

            if (UserProfile.Profile.BannerFile is not null)
                fileNameBanner = await CreateFile(UserProfile.Profile.BannerFile, "imagesProfile/banner");
            else
                fileNameBanner = UserProfile.Profile.Banner!;

            if (UserProfile.Profile.ProfilePictureFile is not null)
                fileNameProfilePicture = await CreateFile(UserProfile.Profile.ProfilePictureFile, "imagesProfile/avatar");
            else
                fileNameProfilePicture = UserProfile.Profile.ProfilePicture!;

            var user = await _userManager.GetUserAsync(User);
            var profileToUpdate = await _context.Profiles.FirstOrDefaultAsync(p => p.User.Id == user!.Id);

            DeleteFile(profileToUpdate!.Banner!, fileNameBanner, "banner");
            DeleteFile(profileToUpdate.ProfilePicture!, fileNameProfilePicture, "avatar");
            
            profileToUpdate.Bio = UserProfile.Profile.Bio;
            profileToUpdate.Location = UserProfile.Profile.Location;
            profileToUpdate.Website = UserProfile.Profile.Website;
            profileToUpdate.Banner = fileNameBanner;
            profileToUpdate.ProfilePicture = fileNameProfilePicture;
            profileToUpdate.User = user;
            profileToUpdate.UserProfileId = UserProfile.Profile.UserProfileId;
            profileToUpdate.BirthDate = UserProfile.Profile.BirthDate;
            profileToUpdate.FullName = UserProfile.Profile.FullName;

            _context.Update(profileToUpdate);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { UserName = user.UserName });
        }

        return View(UserProfile);
    }

    public async Task<string> CreateFile(
        IFormFile file, 
        string pathString)
    {
        string fileName;

        if (file is null) return Path.Combine(pathString, "default.png");

        var wwwRootPath = _hostEnvironment.WebRootPath;
        fileName = Guid.NewGuid().ToString() + "_" + file.FileName;
        var path = Path.Combine(wwwRootPath + "/" + pathString, fileName);

        using (var fileStream = new FileStream(path, FileMode.Create))
        {
            await file.CopyToAsync(fileStream);
        }
        return fileName;
    }

    public void DeleteFile(
        string  fileName1, string fileName2, string pathString)
    {
        if (fileName1 is not null)
        {
            if (fileName1 != "default.png" && fileName1 != fileName2)
            {
                var path = Path.Combine(_hostEnvironment.WebRootPath + "/imagesProfile/" + pathString ,fileName1);
                Console.WriteLine(path);
                if (System.IO.File.Exists(path))
                    System.IO.File.Delete(path);
            }
        }
    }
}

AcademicShare.Web/Views/Posts/Create.cshtml
@model GetPostDto

@{
    ViewData["Title"] = "Create";
}

<div>
    <h1 class="display-4">Create a Posts</h1>
    <p class="lead">
        Create a new post. Here you can create a new post with a title, content, image and teacher.
    </p>
</div>
<hr>
<div class="row">
    @using (Html.BeginForm("Create", "Posts", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="py-3 mb-0">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-sm-6 my-2">
                <i class="fa-regular fa-address-card"></i>
                <label asp-for="Title" class="control-label"></label>
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-6 my-2">
                <i class="fa-solid fa-chalkboard-user"></i>
                <label asp-for="Teacher" class="control-label"></label>
                @Html.TextBoxFor(m => m.Teacher, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Teacher, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-6 my-2">
                <i class="fa-solid fa-file-export"></i>
                <label asp-for="Image" class="control-label"></label>
                @Html.TextBoxFor(m => m.Image, new { @class = "form-control", type = "file" })
                @Html.ValidationMessageFor(m => m.Image, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-6 my-2">
                <i class="fa-solid fa-file-export"></i>
                <label asp-for="Resume" class="control-label"></label>
                <textarea rows="5" asp-for="Resume" class="form-control"></textarea>
                @Html.ValidationMessageFor(m => m.Resume, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-10">
                <i class="fa-solid fa-paperclip"></i>
                <label asp-for="Content" class="control-label"></label>
                <textarea id="tiny" asp-for="Content" class="form-control"></textarea>
                @Html.ValidationMessageFor(m => m.Content, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="row justify-content-start">
            <div class="col-sm-3 d-grid me-2 mt-1">
                <a class="btn btn-outline-primary" asp-controller="Posts" asp-action="Index" role="button">Return</a>
            </div>
            <div class="col-sm-3 d-grid mt-1">
                <button type="submit" class="btn btn-primary">Create Post</button>
            </div>
        </div>
    }
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://cdn.tiny.cloud/1/iqs46z6w4t1twjwg1fhexhhsmo1k6l39uh2f2sa3lhulqhep/tinymce/7/tinymce.min.js"
        referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea#tiny',
                plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage advtemplate ai mentions tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss markdown',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ],
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });
    </script>
}

AcademicShare.Web/Views/Posts/Delete.cshtml
@model Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PostId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AcademicShare.Web/Views/Posts/Details.cshtml
@model Post

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PostId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AcademicShare.Web/Views/Posts/Edit.cshtml
@model Post

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="py-3 mb-6">
        @using (Html.BeginForm("Edit", "Posts", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="justify-content-start">
                @Html.HiddenFor(model => model.UpdatedAt)
                @Html.HiddenFor(model => model.Posts.Id)
                @Html.HiddenFor(model => model.PostId)
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-sm-6">
                    <label asp-for="Title" class="col-sm-4 col-form-label"></label>
                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-6">
                    <label asp-for="Content" class="col-sm-4 col-form-label"></label>
                    @Html.TextBoxFor(model => model.Content, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-6">
                    <label asp-for="Image" class="col-sm-4 col-form-label"></label>
                    @Html.TextBoxFor(model => model.Image, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-6">
                    <label asp-for="Teacher" class="col-sm-4 col-form-label"></label>
                    @Html.TextBoxFor(model => model.Teacher, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Teacher, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-6">
                    <label asp-for="CreatedAt" class="col-sm-4 col-form-label"></label>
                    @Html.TextBoxFor(model => model.CreatedAt, new { @class = "form-control", disabled = "disabled" })
                    @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-6">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AcademicShare.Web/Views/Posts/Index.cshtml
@model PaginatedList<Post>

@using Microsoft.AspNetCore.Identity

@inject AcademicShareDbContext _context
@inject SignInManager<User> SignInManager

@{
    ViewData["Title"] = "Posts";
}

@section Styles {
    <link rel="stylesheet" href="~/css/Posts.css">
}

<div>
    <h1 class="display-4">Posts</h1>
    <p class="lead">Welcome to the posts page. Here you can see all the posts that have been created by the users.</p>
</div>

<partial name="_SearchPostPartial" model="Model" />

<div class="d-flex justify-content-start mt-4">
    <a asp-action="Create" asp-controller="Posts">
        <button class="btn btn-primary" type="submit">
            Make a Post
            <i class="fa-solid fa-pencil"></i>
        </button>
    </a>
    <a asp-controller="Profile" asp-action="Index" asp-route-UserName="@ViewBag.User.UserName">
        <button class="btn btn-primary mx-3" type="submit">
            View Profile
            <i class="fa-solid fa-address-card"></i>
        </button>
    </a>
    <a asp-controller="Posts" asp-action="LikedPosts" asp-route-UserName="@ViewBag.User.UserName">
        <button class="btn btn-primary" type="submit">
            View Liked Posts
            <i class="fa-solid fa-heart"></i>
        </button>
    </a>
</div>
<hr>

<partial name="_PostPagePartial" model="Model" />

AcademicShare.Web/Views/Posts/LikedPosts.cshtml
@model PaginatedList<Post>

@section Styles {
    <link rel="stylesheet" href="~/css/Posts.css">
}

<div>
    <h1 class="display-4">Liked Posts</h1>
    <p class="lead">Here you can see all the posts you liked</p>
</div>


@if (Model.Count.Equals(0))
{
    <div class="alert alert-info" role="alert">
        You haven't liked any posts yet. Click <a href="/Posts">here</a> to see all posts.
    </div>
}
else
{
    @Html.PartialAsync("_SearchPostPartial", Model)
    <div class="d-flex justify-content-start mt-4">
        <a asp-action="Create" asp-controller="Posts">
            <button class="btn btn-primary" type="submit">
                Make a Post
                <i class="fa-solid fa-pencil"></i>
            </button>
        </a>
        <a asp-controller="Profile" asp-action="Index" asp-route-UserName="@ViewBag.User.UserName">
            <button class="btn btn-primary mx-3" type="submit">
                View Profile
                <i class="fa-solid fa-address-card"></i>
            </button>
        </a>
        <a asp-controller="Posts" asp-action="Index" asp-route-UserName="@ViewBag.User.UserName">
            <button class="btn btn-primary" type="submit">
                View All Posts
                <i class="fa-solid fa-newspaper"></i>
            </button>
        </a>
    </div>
    <hr>
    <partial name="_PostPagePartial" model="@Model" />
}