AcademicShare.Web/Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AcademicShare.Web.Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using AcademicShare.Web.Models;
using AcademicShare.Web.Models.Dtos;
using AutoMapper;
using AcademicShare.Web.Models.Paginated;
using System;

namespace AcademicShare.Web.Controllers;

[Authorize]
public class PostsController : Controller
{
    private readonly AcademicShareDbContext _context;
    private readonly SignInManager<User> _signInManager;
    private readonly UserManager<User> _userManager;
    private readonly IWebHostEnvironment _hostEnvironment;
    private readonly IMapper _mapper;

    public PostsController(
        AcademicShareDbContext context,
        UserManager<User> userManager,
        SignInManager<User> signInManager,
        IWebHostEnvironment hostEnvironment,
        IMapper mapper)
    {
        _context = context;
        _signInManager = signInManager;
        _userManager = userManager;
        _hostEnvironment = hostEnvironment;
        _mapper = mapper;
    }

    [HttpGet]
    public async Task<IActionResult> Index(
        string searchString,
        int? pageNumber,
        string sortOrder)
    {
        ViewData["CurrentSort"] = sortOrder;
        if (searchString != null)
        {
            pageNumber = 1;
        }

        if (_context.Posts == null) return Problem("Entity set is null.");

        var posts = from m in _context.Posts
                    select m;

        if (!string.IsNullOrEmpty(searchString))
            posts = posts.Where(s => s.Title!.Contains(searchString));

        ViewBag.User = await _context.Users.FirstOrDefaultAsync(p => p.Id == _userManager.GetUserId(User));

        int pageSize = 9;
        return View(
            await PaginatedList<Post>.CreateAsync(
            posts.OrderByDescending(c => c.CreatedAt)
                .AsNoTracking()
                .Include(p => p.Posts)
                .Include(p => p.Comments)
                .Include(p => p.Likes),
            pageNumber ?? 1, pageSize));
    }

    // GET: Posts/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null) return NotFound();

        var post = await _context.Posts
            .FirstOrDefaultAsync(m => m.PostId.Equals(id));
        if (post == null) return NotFound();

        return View(post);
    }

    public IActionResult Create() => View();


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(
        [Bind(include: "Title,Content,Image,Teacher,Resume")] GetPostDto post)
    {
        if (ModelState.IsValid)
        {
            var fileName = string.Empty;
            if (post.Image is not null)
            {
                var wwwRootPath = _hostEnvironment.WebRootPath;
                fileName = Guid.NewGuid().ToString() + "_" + post.Image.FileName;
                var path = Path.Combine(wwwRootPath + "/imagesPost/", fileName);

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await post.Image.CopyToAsync(fileStream);
                }

            }
            else fileName = "default.png";

            Console.WriteLine(post.Resume);

            var newPost = _mapper.Map<Post>(post);
            newPost.Image = fileName;
            newPost.CreatedAt = DateTime.Now;
            newPost.UpdatedAt = DateTime.Now;
            newPost.Posts = await _userManager.GetUserAsync(User);

            _context.Add(newPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(post);
    }

    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null) return NotFound();

        var post = await _context.Posts.AsNoTracking().FirstOrDefaultAsync(p => p.PostId.Equals(id));
        if (post == null) return NotFound();
        return View(post);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(
        Guid id,
        [Bind("PostId,Title,Content,Image,Teacher,CreatedAt,UpdatedAt,UserId")] Post post)
    {
        if (!id.Equals(post.PostId)) return NotFound();

        if (ModelState.IsValid)
        {
            try
            {
                var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == post.Posts.Id);
                post.Posts = user!;
                post.UpdatedAt = DateTime.Now;
                _context.Update(post);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PostExists(post.PostId)) NotFound();
                else throw;
            }
            return RedirectToAction(nameof(Index));
        }
        return View(post);
    }

    // GET: Posts/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null) NotFound();

        var post = await _context.Posts.FirstOrDefaultAsync(m => m.PostId.Equals(id));

        if (post == null) NotFound();

        return View(post);
    }

    // POST: Posts/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var post = await _context.Posts.FindAsync(id);
        if (post != null)
            _context.Posts.Remove(post);

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    [HttpGet, ActionName("ViewPost")]
    public async Task<IActionResult> ViewPost(Guid id)
    {
        if (id.Equals(null)) return NotFound();

        var post = await _context.Posts.AsNoTracking().FirstOrDefaultAsync(p => p.PostId.Equals(id));

        if (post == null) return NotFound();

        ViewPostDto postView = _mapper.Map<Post, ViewPostDto>(post);

        return View(postView);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ViewPost(
        [Bind(include: "CommentContent,PostId")]
        ViewPostDto Postcomment)
    {
        if (Postcomment == null) return NotFound();
        if (ModelState.IsValid)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == _userManager.GetUserId(User));

            #pragma warning disable CS8601 // Possible null reference assignment.
            var Comment = new Comment
            {
                Content = Postcomment.CommentContent,
                Post = await _context.Posts.FirstOrDefaultAsync(p => p.PostId.Equals(Postcomment.PostId)),
                User = user,
                CreatedAt = DateTime.Now,
            };
            #pragma warning restore CS8601 // Possible null reference assignment.
            _context.Comments.Add(Comment);

            await _context.SaveChangesAsync();

            return RedirectToAction("ViewPost", new { id = Postcomment.PostId });
        }
        return View(Postcomment);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> IndexLike(
        [Bind(include: "PostId")]
        ViewPostDto posts)
    {
        if (posts == null) return NotFound();
        var existingLikes = _context.Likes.Where(l => l.Post.PostId.Equals(posts.PostId) && l.User.Id == _userManager.GetUserId(User));

        if (existingLikes.Any())
        {
            _context.Likes.RemoveRange(existingLikes);
            await _context.SaveChangesAsync();

            return RedirectToAction("ViewPost", new { id = posts.PostId });
        }

        #pragma warning disable CS8601 // Possible null reference assignment.
        var like = new Like
        {
            Post = await _context.Posts.FirstOrDefaultAsync(p => p.PostId.Equals(posts.PostId)),
            User = await _context.Users.FirstOrDefaultAsync(u => u.Id == _userManager.GetUserId(User)),     
        };
        #pragma warning restore CS8601 // Possible null reference assignment.
        _context.Likes.Add(like);

        await _context.SaveChangesAsync();
        return RedirectToAction("ViewPost", new { id = posts.PostId });
    }

    [HttpGet]
    public async Task<IActionResult> LikedPosts(
        string UserName,
        string searchString,
        int? pageNumber,
        string sortOrder)
    {
        ViewData["CurrentSort"] = sortOrder;

        if (searchString != null)
        {
            pageNumber = 1;
        }

        var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == _userManager.GetUserId(User));
        var likedPosts = _context.Likes.Where(l => l.User.Id == user.Id).Select(l => l.Post.PostId);
        var posts = _context.Posts.Where(p => likedPosts.Contains(p.PostId));

        var likedPostsList = from m in posts
                             select m;
        
        if (!string.IsNullOrEmpty(searchString))
            likedPostsList = likedPostsList.Where(s => s.Title!.Contains(searchString));

        ViewBag.User = await _context.Users.FirstOrDefaultAsync(p => p.Id == _userManager.GetUserId(User));
        
        int pageSize = 9;
        return View(await PaginatedList<Post>.CreateAsync(
            likedPostsList.OrderByDescending(c => c.CreatedAt).AsNoTracking(), pageNumber ?? 1, pageSize));
    }

    private bool PostExists(Guid id) => _context.Posts.Any(e => e.PostId.Equals(id));
}

AcademicShare.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using AcademicShare.Web.Models.Dtos;
using AcademicShare.Web.Context;
using AcademicShare.Web.Models.Paginated;
using Microsoft.AspNetCore.Identity;
using AutoMapper;
using System.Data.Entity;

namespace AcademicShare.Web.Controllers;


[Route("[controller]")]
public class UserController : Controller
{
    private readonly ILogger<Like> _logger;
    private readonly AcademicShareDbContext _context;
    private readonly UserManager<User> _userManager;
    private readonly SignInManager<User> _signInManager;
    public UserController(
        ILogger<Like> logger,
        AcademicShareDbContext context,
        UserManager<User> userManager,
        SignInManager<User> signInManager)
    {
        _logger = logger;
        _context = context;
        _userManager = userManager;
        _signInManager = signInManager;
    }

    [HttpGet]
    public async Task<IActionResult> Index(string SearchString, int page = 1, int pageSize = 10)
    {
        if(SearchString != null)
        {
            page = 1;
        }

        var users = _context.Users;
        
        var usersList = from m in users
                        select m;
        
        if (!string.IsNullOrEmpty(SearchString))
            usersList = usersList.Where(s => s.UserName!.Contains(SearchString));

        return View(await PaginatedList<User>.CreateAsync(
            usersList.AsNoTracking(), page, pageSize));
    }
}

AcademicShare.Web/Views/Shared/_EditPostsPartial.cshtml
@model ViewProfileDto

<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasWithBackdrop"
    aria-labelledby="offcanvasWithBackdropLabel">

    <div class="offcanvas-header">
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>

    <div class="offcanvas-body">

        <form method="post" asp-action="Index" enctype="multipart/form-data">
            <h2>Update your Profile</h2>
            <hr />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Profile.UserProfileId" />
            <input type="hidden" asp-for="Profile.ProfilePicture" />
            <input type="hidden" asp-for="Profile.Banner" />
            <div class="form-floating mb-3">
                <input asp-for="Profile.FullName" class="form-control" />
                <label asp-for="Profile.FullName" class="form-label">Full Name</label>
                <span asp-validation-for="Profile.FullName" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Profile.Bio" class="form-control" aria-required="true" />
                <label asp-for="Profile.Bio" class="form-label">Bio</label>
                <span asp-validation-for="Profile.Bio" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Profile.Location" class="form-control" aria-required="true" />
                <label asp-for="Profile.Location" class="form-label">Location</label>
                <span asp-validation-for="Profile.Location" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Profile.Website" class="form-control" aria-required="true" />
                <label asp-for="Profile.Website" class="form-label">Website</label>
                <span asp-validation-for="Profile.Website" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Profile.BirthDate" class="form-control" aria-required="true" type="date" />
                <label asp-for="Profile.BirthDate" class="form-label">Date Of Birth</label>
                <span asp-validation-for="Profile.BirthDate" class="text-danger"></span>
            </div>
            <div class="col-4">
                <img src="htttps://placehold.js/150x150" id="PrevImg" class="img-thumbnail" style="width:100px;height:100px" />
            </div>
            <div class="mb-3">
                <label asp-for="Profile.BannerFile" class="form-label">Banner</label>
                <input type="file" id="ChosseImg" asp-for="Profile.BannerFile" class="form-control" aria-required="true" />
                <span asp-validation-for="Profile.BannerFile" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Profile.ProfilePictureFile" class="form-label">Profile Picture</label>
                <input type="file" asp-for="Profile.ProfilePictureFile" class="form-control" placeholder="@Model.Profile.ProfilePicture"/>
                <span asp-validation-for="Profile.ProfilePictureFile" class="text-danger"></span>
            </div>

            <div class="mt-4">
                <button type="submit" class="w-100 btn btn-lg btn-primary">Update</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="imgLoad.js" />
}

AcademicShare.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AcademicShare</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AcademicShare.Web.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    @RenderSection("Styles", required: false)
</head>

<body>
    <header>
        <nav
            class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3 p-3 justify-content-around" style="font-family: jost; font-weight: 600;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="/imagesSite/logo.svg" alt="Logo" width="30" height="30"
                        class="d-inline-block align-text-top">
                    AcademicShare</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-around">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Posts"
                                asp-action="Index">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Posts"
                                asp-action="Create">Create Post</a>
                        </li>
                    </ul>
                    <Partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="container">
            &copy; 2024 - AcademicShare.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/b728800987.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

AcademicShare.Web/Views/Shared/_LinksPartial.cshtml
@model ViewProfileDto

@if (Model.Profile.BirthDate is not null)
{

    <div class="my-2">
        <a style="font-weight: 500;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar3"
                viewBox="0 0 16 16">
                <path
                    d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2M1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857z" />
                <path
                    d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2" />
            </svg>
            @Model.Profile.BirthDate
        </a>
    </div>
}
@if (Model.Profile.Website is not null)
{
    <div class="my-2">
        <a style="font-weight: 500;">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-link-45deg"
                viewBox="0 0 16 16">
                <path
                    d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1 1 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4 4 0 0 1-.128-1.287z" />
                <path
                    d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243z" />
            </svg>
            <a href="@Model.Profile.Website" class="text-decoration-none" style="color: #101a1f;">@Model.Profile.Website</a>
        </a>
    </div>
}
@if (Model.Profile.Location is not null)
{
    <div class="my-2">
        <a style="font-weight: 500;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt"
                viewBox="0 0 16 16">
                <path
                    d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A32 32 0 0 1 8 14.58a32 32 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10" />
                <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4m0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />
            </svg>
            @Model.Profile.Location
        </a>
    </div>
}

AcademicShare.Web/Views/Shared/_PostPagePartial.cshtml
@model PaginatedList<Post>

@using Microsoft.AspNetCore.Identity

@inject AcademicShareDbContext _context
@inject SignInManager<User> SignInManager

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<div class="row row-cols-1 row-cols-md-2 g-4">
    @foreach (var item in Model)
    {
        <div class="col">
            <div class="card h-100">
                <img src="/imagesPost/@Html.DisplayFor(modelItem => item.Image)" class="card-img-top" alt="@Html.DisplayFor(modelItem => item.Title)">
                <div class="card-body">
                    <div class="d-inline-flex w-100 m-auto">
                        <img src="/imagesProfile/avatar/@_context.Profiles.FirstOrDefault(u => u.User.Id.Equals(item.Posts.Id)).ProfilePicture"
                            alt="" class="rounded-circle me-2" style="width: 55px; height: 55px; object-fit: cover;">
                        <div class="align-content-center">
                            <p class="card-text mx-1 mb-0" style="font-size: large;">@Html.DisplayFor(modelItem =>
                            _context.Profiles.FirstOrDefault(u => u.User.Id.Equals(item.Posts.Id!)).FullName)</p>
                            <p class="card-text mx-1 mb-0 text-muted" style="font-size: medium;">#@Html.DisplayFor(
                                modelItem => _context.Users.FirstOrDefault(u => u.Id == item.Posts.Id!).UserName)</p>
                        </div>
                    </div>
                    <hr>
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h5>
                    <p class="card-text text-break">@Html.DisplayFor(modelItem => item.Resume)</p>
                    <p class="card-text text-muted mb-0">Teacher: @Html.DisplayFor(modelItem =>
                    item.Teacher)</p>
                    <p class="card-text"><small class="text-muted">@Html.DisplayFor(modelItem => item.CreatedAt)</small></p>
                    <a asp-action="ViewPost" asp-controller="Posts" asp-route-id="@item.PostId" class="btn btn-primary">View
                        the content
                    </a>
                    <div class="d-flex align-content-center mx-1 mt-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                            class="bi bi-chat" viewBox="0 0 16 16">
                            <path
                                d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105" />
                        </svg>
                        <p class="mb-0 mx-2">
                            @_context.Comments.Where(c => c.Post.PostId == item.PostId).ToList().Count()
                        </p>
                        @if (_context.Likes.FirstOrDefault(l => l.User.Id == SignInManager.UserManager.GetUserId(User) &&
                       l.Post.PostId == item.PostId) == null)
                        {
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                                class="bi bi-star ms-2" viewBox="0 0 16 16">
                                <path
                                    d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.56.56 0 0 0-.163-.505L1.71 6.745l4.052-.576a.53.53 0 0 0 .393-.288L8 2.223l1.847 3.658a.53.53 0 0 0 .393.288l4.052.575-2.906 2.77a.56.56 0 0 0-.163.506l.694 3.957-3.686-1.894a.5.5 0 0 0-.461 0z" />
                            </svg>
                        }
                        else
                        {
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                                class="bi bi-star-fill" viewBox="0 0 16 16">
                                <path
                                    d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                            </svg>
                        }
                        <p class="mb-0 mx-2">
                            @_context.Likes.Where(c => c.Post.PostId == item.PostId).ToList().Count()
                        </p>
                    </div>
                </div>
            </div>
        </div>
    }
    @if (Model.Count() == 0)
    {
        <p>No data found</p>
    }
</div>
<div class="mt-5 justify-content-center d-flex ">
    <a asp-action="Index" asp-route-pageNumber="@(Model.PageIndex - 1)" class="btn btn-primary m-2 @prevDisabled">
        Previous
    </a>

    <a asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 1)" class="btn btn-primary m-2 @nextDisabled">
        Next
    </a>
</div>

AcademicShare.Web/Views/Shared/_SearchPostPartial.cshtml
@model PaginatedList<Post>

@using(Html.BeginForm("Index", "Posts", FormMethod.Get))
{
    <div class="justify-content-start align-content-center d-flex mt-4">
        <div class="form-floating col-md-5">
            @Html.TextBox("SearchString", null, new { @class = "form-control", @placeholder = "Search title" })
            <label>Search title</label>
        </div>
        <input class="btn btn-primary mx-2 m-auto" type="submit" value="Filter" />
    </div>
}